plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.146'
}

evaluationDependsOnChildren()

version = "${mcversion}-${mod_version}-${tag_lanzador}"
group = "${group}"
base {
    archivesName = "${mod_named}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

def phosResources = rootProject.project(':Phosphophyllite').file('src/main/resources/').getAbsolutePath()
def phosGeneratedResources = rootProject.project(':Phosphophyllite').file('src/generated/resources/').getAbsolutePath()

neoForge {
    version = "${neoversion}"

    accessTransformers.from file('src/main/resources/META-INF/accesstransformer.cfg')
    accessTransformers.from project(':Phosphophyllite').file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
            programArgument '--nogui'
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generatedClient/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', phosResources, '--existing', phosGeneratedResources
        }

        serverData {
            serverData()
            programArguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', phosResources, '--existing', phosGeneratedResources
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            jvmArgument '-Xmx2G'
        }
    }

    mods {
        "${modid}" {
            sourceSet(sourceSets.main)
        }
        phosphophyllite {
            sourceSet(project(':Phosphophyllite').sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    srcDir 'src/generatedClient/resources'
}

repositories {
    mavenCentral()
    maven {
        url = "https://maven.blamejared.com"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    compileOnly project(':Phosphophyllite')
    compileOnly "org.lwjgl:lwjgl-vulkan:${lwjgl_version}"
}

test {
    enabled = false
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${mod_name}",
                "Specification-Vendor"    : "${author}",
                "Specification-Version"   : "1",
                "Implementation-Title"    : "${mod_name}",
                "Implementation-Version"  : "${version}",
                "Implementation-Vendor"   : "${author}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mcversion         : mcversion,
            neoversion        : neoversion,
            loader_version    : loader_version,
            modid             : modid,
            mod_name          : mod_name,
            mod_named         : mod_named,
            mod_version       : mod_version,
            author            : author,
            description       : description,
            license           : license,
            phos_version_range: project.project(':Phosphophyllite').property('compatibility').toString(),
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.getRelease().set(25)
    options.compilerArgs << "-Xmaxerrs" << "2000"
}
