org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=RogueLogix, UnnamedUser12
modid=quartz
mod_name=Quartz
mod_named=Quartz
description=Instanced rendering engine for the BiggerSeries
license=LGPL v2.1
tag_lanzador=NeoForge
group=modernmods.quartzrevived
mod_version=2.0.0
compatibility=[2.0.0,)

# Minecraft and NeoForge versions
mcversion=26.1.2
neoversion=26.1.2.107
loader_version=[4,)

# NeoForge Parchment


neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
lwjgl_version=3.3.3
sodium_version=mc26.1.2-0.9.1-neoforge
iris_version=1.11.2+26.1-neoforge
