org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=RogueLogix, NadienDev
modid=quartz
mod_name=QuartzRevived
mod_named=Quartz Revived
description=Instanced rendering engine for the BiggerSeries
license=LGPL v2.1
tag_lanzador=NeoForge
group=modernmods.quartzrevived
mod_version=1.0.0
compatibility=[1.0.0,)

# Minecraft and NeoForge versions
mcversion=1.21.1
neoversion=21.1.240
loader_version=[4,)

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
lwjgl_version=3.3.3
sodium_version=mc1.21.1-0.6.13-neoforge
iris_version=1.8.12+1.21.1-neoforge
